// <auto-generated />
using System;
using LGym.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGym.Migrations
{
    [DbContext(typeof(LGymContext))]
    partial class LGymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LGym.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            JoinDate = new DateTime(2024, 7, 31, 11, 51, 39, 357, DateTimeKind.Local).AddTicks(9966),
                            LastName = "Doe"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            JoinDate = new DateTime(2024, 7, 31, 11, 51, 39, 358, DateTimeKind.Local).AddTicks(3),
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("LGym.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            Duration = 60,
                            MemberId = 1,
                            SessionDate = new DateTime(2024, 7, 31, 11, 51, 39, 358, DateTimeKind.Local).AddTicks(759),
                            TrainerId = 1
                        },
                        new
                        {
                            SessionId = 2,
                            Duration = 45,
                            MemberId = 2,
                            SessionDate = new DateTime(2024, 7, 31, 11, 51, 39, 358, DateTimeKind.Local).AddTicks(770),
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("LGym.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<decimal>("FeePer30Minutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = 1,
                            FeePer30Minutes = 20.00m,
                            FirstName = "Emily",
                            HireDate = new DateTime(2024, 7, 31, 11, 51, 39, 358, DateTimeKind.Local).AddTicks(686),
                            LastName = "Jones",
                            Speciality = "Yoga"
                        },
                        new
                        {
                            TrainerId = 2,
                            FeePer30Minutes = 25.00m,
                            FirstName = "Michael",
                            HireDate = new DateTime(2024, 7, 31, 11, 51, 39, 358, DateTimeKind.Local).AddTicks(694),
                            LastName = "Brown",
                            Speciality = "Weightlifting"
                        });
                });

            modelBuilder.Entity("LGym.Models.Session", b =>
                {
                    b.HasOne("LGym.Models.Member", "Member")
                        .WithMany("Sessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGym.Models.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("LGym.Models.Member", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LGym.Models.Trainer", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
